miracle:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 172.16.120.234
    port: 3306
    database: share-miracle
    username: root
    password: gcsj1234
  redis:
    host: 172.16.120.234
    port: 6379
    password: gcsj1234
  elasticsearch:
    host: 172.16.120.234
    port: 9200
    username: elastic
    password: 123456
  kafka:
    host: 172.16.120.234
    port: 9092
    #kafka的topic名称
  #    kafkaTopic: topic-test
  mongodb:
    host: 172.16.120.234
    port: 27017
    database: miracle
    username: root
    password: root
