miracle:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 47.236.231.61
    port: 3306
    database: share-miracle
    username: root
    password: gcsj1234
  redis:
    host: localhost
    port: 6379
    password: gcsj1234
  elasticsearch:
    host: 47.236.231.61
    port: 9200
  kafka:
    host: 47.236.231.61
    port: 9092
    #kafka的topic名称
  #    kafkaTopic: topic-test
  mongodb:
    host: 47.236.231.61
    port: 27017
    database: miracle
    username: root
    password: root


