server:
  port: 8080
spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${miracle.datasource.driver-class-name}
      url: jdbc:mysql://${miracle.datasource.host}:3306/share_miracle?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: ${miracle.datasource.username}
      password: ${miracle.datasource.password}
  redis:
    host: ${miracle.redis.host}
    port: ${miracle.redis.port}
    password: ${miracle.redis.password}
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

  elasticsearch:
    uris: ${miracle.elasticsearch.host}:${miracle.elasticsearch.port}
    username: ${miracle.elasticsearch.username}
    password: ${miracle.elasticsearch.password}
  kafka:
    bootstrap-servers: ${miracle.kafka.host}:${miracle.kafka.port}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1  #应答级别:多少个分区副本备份完成时向生产者发送ack确认(可选0、1、all/-1)
    consumer:
      group-id: ${spring.application.name}-ConsumerGroup  # 默认的消费组ID
      enable-auto-commit: false  # 是否自动提交offset
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      missing-topics-fatal: false  # 消费监听接口监听的主题不存在时，自动创建，true时表示如果不存在启动报错
      ack-mode: manual_immediate

  application:
    name: share-miracle
  data:
    mongodb:
      host: ${miracle.mongodb.host}
      port: ${miracle.mongodb.port}
      database: ${miracle.mongodb.database}
      username: ${miracle.mongodb.username}
      password: ${miracle.mongodb.password}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.sharemiracle.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      miracle:
        mapper: debug
        service: info
        controller: info

share-miracle.jwt:
  userSecretKey: gcsj_miracle_share_user_secret_key
  userTtl: 7200000  # 例如用户token有效时间为2小时 单位:毫秒
  userTokenName: authorization

